### PR TITLE
Updating the docs for #3231

### LINKED ISSUE #3231: Replace Faker with @faker-js/faker
#### What are you trying to achieve?

Replace the faker js library as the author has deleted this libarry from github and npm. 

#### What do you get instead?
If you try to installer faker as per the instructions:

`npm install faker`
you get and empty library with the following:
Screenshot 2022-02-05 at 10 02 59

> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
npm install faker
up to date, audited 2 packages in 375ms
found 0 vulnerabilities
ls node_modules/faker
Readme.md    package.json
cat node_modules/faker/Readme.md
What really happened with Aaron Swartz?%
```

The library has now been taken over to https://fakerjs.dev/ and the new install instructions should be reflected in the codecepjs documentation. 

```
npm install @faker-js/faker --save-dev
```

### PR DESCRIPTION
**Pull request by cybersonic**
## Motivation/Description of the PR
- Updates the plugin documentation with regards to the defunct faker libarry
- Resolves #3231

Applicable plugins:
- [] fakerTransform

## Type of change

- [ ] :clipboard: Documentation changes/updates

## Checklist:

- [ ] Documentation has been added (Run `npm run docs`)

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by DavertMik** [comment]
@cybersonic  This documentation is generated from this file https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/plugin/fakerTransform.js
Please update it instead
Thank you

**Review by EgorBodnar — APPROVED** [review]

**Comment by kobenguyent** [comment]
hi @cybersonic any changes to update this PR?

**Comment by cybersonic** [comment]
Apologies, I will have a look now.

**Comment by kobenguyent** [comment]
Thanks @cybersonic for the update. Out of curiosity, would you have chance to check the comment from davert above? 😄

**Comment by cybersonic** [comment]
I did @PeterNgTr ! I am just having issues in my local environment to build the docs. Once I get those sorted I can resubmit

**Pull request closed without merging**
