### PR TITLE
Update WebdriverIO and Filesystem helper links

### PR DESCRIPTION
**Pull request by jinjorge**
helper links were pointing to non-existent pages.

### CODE REVIEW

**Comment by sergeyklay** [comment]
Can you please create PR to the `2.1` branch?

**Comment by jinjorge** [comment]
@sergeyklay where's the 2.1 branch?

screen shot 2015-12-18 at 4 20 42 pm

**Comment by sergeyklay** [comment]
Oops :) Messed up with https://github.com/Codeception/Codeception
It's time to bed

**Comment by DavertMik** [comment]
Thank you )

**Pull request merged**
