### PR TITLE
fix: TestCafe grabAttributeFrom method not works

### PR DESCRIPTION
**Pull request by elukoyanov**
## Motivation/Description of the PR

Applicable helpers:

- [ ] Webdriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] Appium
- [ ] Protractor
- [x] TestCafe

- Description of this PR, which problem it solves
`grabAttributeFrom()` method not returning the attribute value

- A link to the corresponding issue (if applicable).
https://stackoverflow.com/questions/59133688/grabattributefrom-method-not-returning-the-attribute-value

## Type of change

- [ ] Breaking changes
- [ ] New functionality
- [x] Bug fix
- [ ] Documentation changes/updates
- [ ] Hot fix
- [ ] Markdown files fix - not related to source code

## Checklist:

- [x] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by DavertMik** [comment]
Seems fine, but test failed

**Comment by DavertMik** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- test/helper/webapi.js  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/CodeceptJS/CodeceptJS/pullRequest?prid=4615435&bid=15480130)

**Comment by DavertMik** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- test/helper/webapi.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/CodeceptJS/CodeceptJS/pullRequest?prid=4615435&bid=15480130)

**Comment by DavertMik** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- test/helper/webapi.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/CodeceptJS/CodeceptJS/pullRequest?prid=4615435&bid=15480130)

**Comment by elukoyanov** [comment]
Don't understand, why travis build for TestCafe fails every time with catched error from previous test

And why circle-ci with webdriver fails

**Comment by DavertMik** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- test/helper/webapi.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/DavertMik/CodeceptJS/pullRequest?prid=4615435&bid=15480130)

**Comment by DavertMik** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- test/helper/webapi.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/DavertMik/CodeceptJS/pullRequest?prid=4615435&bid=15480130)

**Comment by DavertMik** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- test/helper/webapi.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/DavertMik/CodeceptJS/pullRequest?prid=4615435&bid=15480130)

**Comment by elukoyanov** [comment]
Skipped some failing tests for TestCafe.

But somewhy Webdriverio tests fails in Circle CI, does not know why.

**Comment by elukoyanov** [comment]
Looks like we have a problem with test. Cause if some test in test suite thows error (and catches it), then all next tests fails

**Comment by elukoyanov** [comment]
webdriverio v5.16.12 was released between first (passed) and second (failed) circle CI builds.

https://github.com/webdriverio/webdriverio/releases

**Comment by DavertMik** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- test/helper/webapi.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/DavertMik/CodeceptJS/pullRequest?prid=4615435&bid=15480130)

**Comment by DavertMik** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- test/helper/webapi.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/DavertMik/CodeceptJS/pullRequest?prid=4615435&bid=15480130)

**Comment by DavertMik** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- test/helper/webapi.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/DavertMik/CodeceptJS/pullRequest?prid=4615435&bid=15480130)

**Pull request merged**
