### PR TITLE
Add nodeJs debugger support

### PR DESCRIPTION
**Pull request by APshenkin**
fix https://github.com/Codeception/CodeceptJS/issues/559 - "codeceptjs run --debug-brk" does nothing

Now there is two options --debug-brk and --inspect that passes to NodeJs and allow you to run NodeJs inspectors

### CODE REVIEW

**Comment by DavertMik** [comment]
How stable is such approach?
Will process won't stuck and can it be interrupted by Ctrl-C?

**Comment by DavertMik** [comment]
I think this feature needs some testing before going to release

**Comment by APshenkin** [comment]
@DavertMik 
You can interrupt process by Ctrl-C in debug mode. Process will stuck on first line of code to give user opportunity to set breakpoints in test code.

I take implementation of this feature from mocha framework https://github.com/mochajs/mocha/blob/master/bin/mocha. So I think it's save to use this feature

**Comment by APshenkin** [comment]
@DavertMik You are right, we have to test it deeply. These changes break debug mode in Webstorm. I'll investigate this

**Comment by Vorobeyko** [comment]
When will this feature be implemented?
I am really want this feature(

**Comment by jlewisCode** [comment]
any updates to this or does this need to be picked up by someone?

**Comment by DavertMik** [comment]
@APshenkin are you still on this?
Maybe someone could take it?

**Comment by DavertMik** [comment]
According to reports in Slack, debugger works even without this PR :v:

**Comment by pstoica** [comment]
You can't pass `debug-brk` to the codecept command itself. My goal was to reuse my existing npm scripts with VSCode's debug launchers, but you have to rewrite the commands to use `node $NODE_DEBUG_OPTIONS codeceptjs`. Perhaps this is worth revisiting?

**Pull request closed without merging**
