### PR TITLE
(Deprecated): drop WebDriverIO v4 helper

### LINKED ISSUE #2209: Drop WebdriverIO helper
WebDriverIO helper is deprecated helper.

### PR DESCRIPTION
**Pull request by PeterNgTr**
## Motivation/Description of the PR
- Remove the WebDriverIO helper (wdio v4) everywhere
- Resolves #2209

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by DavertMik** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ lib/helper/Protractor.js  -9
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DavertMik/CodeceptJS/pullRequest?prid=5321938&bid=17416923)

**Comment by Vorobeyko** [comment]
this pr need merge to Codeception:codeceptjs-v3.0

**Comment by PeterNgTr** [comment]
> this pr need merge to Codeception:codeceptjs-v3.0

@Vorobeyko done :)

**Comment by PeterNgTr** [comment]
> why did you not remove helper webdriverio ?

oh, it's missing when I rebased.

**Comment by PeterNgTr** [comment]
> There are code in WebDriver.js:
> 
> ```
>     if (webdriverio.VERSION && webdriverio.VERSION.indexOf('4') === 0) {
>       throw new Error(`This helper is compatible with "webdriverio@5". Current version: ${webdriverio.VERSION}. Please upgrade webdriverio to v5+ or use WebDriverIO helper instead`);
>     }
> ```
> 
> 1. we remove `webdriverio`, so it can't be an alternative variant.
> 2. maybe we should tell to prior to use v6 but can v5 too
> 
> Should we remove this rows or simple change message?

I think we'll go with removing it, cause we already inform user the v5 deprecated in this code

```js
    if (isWebDriver5()) {
      console.log('DEPRECATION NOTICE:');
      console.log('You are using webdriverio v5. It is recommended to update to webdriverio@6.\nSupport of webdriverio v5 is deprecated and will be removed in CodeceptJS 3.0\n');
    }
```

**Comment by PeterNgTr** [comment]
> runio.js has 'WebDriverIO', 'SeleniumWebdriver' using too

removed them in `runio.js`

**Comment by elukoyanov** [comment]
it's okey, but one question:

> Support of webdriverio v5 is deprecated and will be removed in CodeceptJS 3.0

we will support only v6 in Codecept3.0?

**Pull request merged**
