### PR TITLE
Fix/1422 save screenshot on windows

### PR DESCRIPTION
**Pull request by PeterNgTr**
@hubidu can you try to test this fix on windows?

### CODE REVIEW

**Comment by DavertMik** [comment]
Sorry, I'm not taking library from 2015 on board.
Maybe it is something regular `path` can do?

**Comment by PeterNgTr** [comment]
Will find another solution ^^

**Comment by LukoyanovE** [comment]
@peterngtr, looks pretty simple)

**Comment by DavertMik** [comment]
Thanks!

**Pull request merged**
