### PR TITLE
feat: wdio with devtools protocol

### PR DESCRIPTION
**Pull request by kobenguyent**
## Motivation/Description of the PR
- Open another possibility to run Webdriver Helper tests using devtools protocol -> https://webdriver.io/docs/automationProtocols/#devtools-protocol

### Running with devtools protocol

```js
{
   helpers: {
     WebDriver : {
       url: "http://localhost",
       browser: "chrome",
       devtoolsProtocol: true,
       desiredCapabilities: {
         chromeOptions: {
           args: [ "--headless", "--disable-gpu", "--no-sandbox" ]
         }
       }
     }
   }
}
```

Applicable helpers:
- [ ] WebDriver

## Type of change
- [ ] :rocket: New functionality

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by kobenguyent** [comment]
> Hi @kobenguyent feat: wdio with devtools protocol #4105 can we use the codeceptjs geolocation function?

yes that's possible when using devtools protocol -> https://github.com/codeceptjs/CodeceptJS/pull/4105/files#diff-7d8b1b9f1557e5e6307a9f1a97c1cbf9731239061de79bd62d452f39510dee65R1142

**Comment by kobenguyent** [comment]
> Can you please share an example, and what prerequisites are needed here?
> 
> "codeceptjs": "^3.5.11", "webdriver": "^8.27.0", "webdriverio": "^8.27.0" "selenium-standalone": "9.3.1",
> 
> Capabilities set to devtoolsProtocol: true,

sure @autotest-web once this PR is merged and released, in your WebDriver config

```
WebDriver : {
...
       devtoolsProtocol: true, // add this option and you're good to go with using setGeoLocation
       ...
     }
```

**Review by Arhell — APPROVED** [review]

**Comment by kobenguyent** [comment]
Hey @autotest-web usually, we'd to release regularly however due to many factors that won't happen as expected. So we will announce the release once it happens.

**Comment by kobenguyent** [comment]
I'm eager, too.

**Comment by kobenguyent** [comment]
Screenshot 2024-01-17 at 13 41 35
hi @autotest-web just tried and it worked for me.

**Comment by kobenguyent** [comment]
Screenshot 2024-01-18 at 07 45 37
I don't know if the url should change to .cn but at least for me, the geolocation is set as expected.

**Comment by kobenguyent** [comment]
Nice! Glad that you made it. Regarding the url changes I think that's related to the IP detection.

**Comment by kobenguyent** [comment]
https://github.com/webdriverio/webdriverio/issues/7551#issuecomment-943742547

Per wdio, there is no chance to implement this command using DevTools and Puppeteer (which drivers CDP).

**Pull request merged**
