### PR TITLE
add option noreverse

### PR DESCRIPTION
**Pull request by APshenkin**
Add option --noreverse for cli reporter
This option check should we reverse failed steps output or not.

### CODE REVIEW

**Comment by DavertMik** [comment]
Sorry but what does `reverse output` mean? ;)

**Comment by APshenkin** [comment]
@DavertMik 
Currently failure steps output is reversed:
e.g.
```
// test code
I.amOnPage('/');
I.see('blabla');

//failure output
We didn't receive message for order (1502852) with state ((order) => order._embedded.counterProposals[0].status === 'approved' && order.quantity === 2). Check additional context to see latest message for this order we receive

Scenario Steps:
// here is error message
...
// here is reversed steps output
- I.see("blabla") at Test.<anonymous> (tests/test.js:159:20)
- I.amOnPage("/") at Test.<anonymous> (test/test.js:158:20)
```

with --noreverse option steps output will be:

```
- I.amOnPage("/") at Test.<anonymous> (test/test.js:158:20)
- I.see("blabla") at Test.<anonymous> (tests/test.js:159:20)
```

**Comment by DavertMik** [comment]
Once I figure out how to update documentation to make this clear I will merge the PR 😄

**Comment by DavertMik** [comment]
I think this option has no big sense anymore as we have Allure reporter
Probably you should use it, and leave CLI reporter as simple as possible

**Pull request closed without merging**
