### PR TITLE
Add the method translation of Chinese

### PR DESCRIPTION
**Pull request by TechQuery**
One question: [ISO 639.1](http://www.loc.gov/standards/iso639-2/php/code_list.php) or [RFC 4646](http://www.ietf.org/rfc/rfc4646.txt) should I follow on the language name ?

### CODE REVIEW

**Comment by DavertMik** [comment]
> One question: ISO 639.1 or RFC 4646 should I follow on the language name ?

Sorry, I have no idea 😟
So choose whatever you like and thanks. That's really awesome!

**Comment by TechQuery** [comment]
I chose our customary usage, it's OK to merge it.

**Comment by DavertMik** [comment]
Thanks!

**Comment by TechQuery** [comment]
But the document on official website has not been updated.

**Pull request merged**
