### PR TITLE
add geoLocation methods

### PR DESCRIPTION
**Pull request by PeterNgTr**
Introduce two methods:
- getGeoLocation()
- setGeoLocation()

### CODE REVIEW

**Comment by DavertMik** [comment]
Maybe to keep general style we should use `grabGeolocation` ?

**Comment by PeterNgTr** [comment]
> Maybe to keep general style we should use `grabGeolocation` ?

Sure, that's nice. I would make the change!

**Comment by DavertMik** [comment]
Accepted!

**Comment by DavertMik** [comment]
Thanks!

**Pull request merged**
