### PR TITLE
chore(docs): config name consistency

### PR DESCRIPTION
**Pull request by JiLiZART**
## Motivation/Description of the PR

This is a second part of config name consistency of https://github.com/codeceptjs/CodeceptJS/pull/3195

This PR changes only docs files as described in previous PR

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [ ] :bug: Bug fix
- [x] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [x] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by kobenguyent** [comment]
our code is still initializing the `conf.js`. Shall we update it too? https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/command/init.js#L77

**Comment by JiLiZART** [comment]
Good question. I can do it in separate PR.

**Comment by DavertMik** [comment]
Thanks, due to war in :ukraine: and lot of work on my primary business I don't have time and energy at this moment to enforce this change. I'm not closing this PR. But I need some more time to merge it and to ensure it is absolutely consistent with overall code we have. 

Thanks. I hope to return to this in May

**Comment by DavertMik** [comment]
Sorry, I don't think I will have time to invest into this change
This will take too much effort and can affect lots of details 
It's just naming and no rule says how config files should be named.
So I will prefer to keep things as they are

**Pull request closed without merging**
