### PR TITLE
fix: docs format

### PR DESCRIPTION
**Pull request by kobenguyent**
## Motivation/Description of the PR
- Due to the [lib](https://documentation.js.org) that we are using to generate docs, the fast and cheap way to fix those format issue is moving the texts to above the mustache template.

## Type of change
- [ ] :clipboard: Documentation changes/updates
- [ ] :hammer: Markdown files fix - not related to source code

## Checklist:
- [ ] Documentation has been added (Run `npm run docs`)

### CODE REVIEW

**Comment by kobenguyent** [comment]
FYI: @Horsty80 @elbotho as you are currently touching the fix for documentation.

updated the contribution guide: https://github.com/codeceptjs/CodeceptJS/blob/3.x/.github/CONTRIBUTING.md#documentation

**Comment by Horsty80** [comment]
> FYI: @Horsty80 @elbotho as you are currently touching the fix for documentation.
> 
> updated the contribution guide: https://github.com/codeceptjs/CodeceptJS/blob/3.x/.github/CONTRIBUTING.md#documentation

Oh ! You are right i didnt check existing PR before doing mine ^^’

just one question, what is the purpose of the npm docs command that you mention ? 
The doc isn’t just the md files ?

**Comment by kobenguyent** [comment]
well, I'm not sure if that's correct, but per my best knowledge, docs that we see on website https://codecept.io/ are involving multiple steps.

Long story short : After you updated docblock in JS file, generate markdown files with next command:
`npm run docs`

**Comment by elbotho** [comment]
@kobenguyent thank you! I'm glad that this approach does not mess with the titles (as I would have expected).

**Review by Arhell — APPROVED** [review]

**Pull request merged**
