### PR TITLE
Playwright fixes - Work in progress

### PR DESCRIPTION
**Pull request by Georgegriff**
## Motivation/Description of the PR
- Fixing issues with playwright
- Fixed waitForValue so far

Applicable helpers:

- [ ] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [/ ] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] puppeteerCoverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] wdio

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [ ] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by Georgegriff** [comment]
@DavertMik hopefully this fixes some of the playwright tests

**Comment by Georgegriff** [comment]
Any other failures i suspect are things i missed that were broken in in the playwright 0.12.1 API changes

**Comment by Georgegriff** [comment]
Need some help with `execureAsync` `waitForClickable`and `scrollTo` think these might have been broken in 0.12 and I missed them

**Comment by DavertMik** [comment]
Thank you!

**Pull request merged**
