### PR TITLE
Introduce key alias for pressing modifier depending on operating system

### PR DESCRIPTION
**Pull request by martomo**
* Replacing `detectOS` option with key alias (e.g. `'CommandOrControl'`) which will press `'Control'` or `'Meta'` depending on operating system.
* Additional aliases for `'Meta'` (`'Cmd'`, `'OS'`, `'Super'`) and properly detect `'AltGraph'`.

### CODE REVIEW

**Comment by martomo** [comment]
@DavertMik This should address the matter regarding `detectOS` option as pointed out in https://github.com/Codeception/CodeceptJS/pull/1952#issuecomment-541873117, by replacing it with a key alias (`CommandOrControl`).

Would it be possible to include this in the next release (https://github.com/Codeception/CodeceptJS/pull/1956#pullrequestreview-301641099)?
By including this solution in the next release, there would be no need to support `detectOS` option (in helper/test config) for any future releases.

**Comment by DavertMik** [comment]
Thanks! This patch is a way better. However, now I need to merge it on top of a previous one :)

**Comment by martomo** [comment]
Give me a couple minutes and I'll create a new branch based from 2.3.3-release.

**Comment by martomo** [comment]
Closing in favour of #1960, which can be merged directly to release 2.3.3 branch.

**Pull request closed without merging**
