### PR TITLE
feat: highlight the interacting elements

### LINKED ISSUE #3476: How to highlight fields
#### What are you trying to achieve?

Is there a way to highlight the fields of elements (with a border or any CSS of our choice) when codeceptJS is clicking or filling them? This will provide good feedback on what field(s) in the page the script is interacting with.

### PR DESCRIPTION
**Pull request by kobenguyent**
## Motivation/Description of the PR
- Resolves #3476 
1685458918788_Incorrect_username_or_password..passed.webm
Screenshot 2023-05-30 at 17 26 01

Applicable helpers:
- [x] Puppeteer
- [x] Playwright
- [x] Webdriver

## Type of change
- [x] :rocket: New functionality

## Checklist:
- [x] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by DavertMik** [comment]
Wow!

**Review by DavertMik — APPROVED** [review]
So simple yet awesome!
I would somehow turn that on if I run tests with `--debug` flag,
Can we also have it for WebDriver?

**Review by DavertMik — APPROVED** [review]
So simple yet awesome!
I would somehow turn that on if I run tests with `--debug` flag,
Can we also have it for WebDriver?

**Comment by DavertMik** [comment]
@kobenguyent please fix Puppeteer tests

**Comment by DavertMik** [comment]
@kobenguyent I think that would be essential thing for writing tests with AI 
as you will see all options while writing it

**Comment by kobenguyent** [comment]
> So simple yet awesome! I would somehow turn that on if I run tests with `--debug` flag, Can we also have it for WebDriver?

Webdriver support is added. I'm not sure how to acknowledge is the --debug is passed. May you advise on that?

> @kobenguyent please fix Puppeteer tests

Oh, fixed it.

**Comment by EgorBodnar** [comment]
🔥🔥

**Review by Arhell — APPROVED** [review]

**Comment by DavertMik** [comment]
Seems good to me. Let's have it!

**Comment by incoming-th** [comment]
@kobenguyent Thanks a lot, pretty sure next someone will ask to customize the border width and the color :D

**Comment by incoming-th** [comment]
@kobenguyent Quick note, this seems to not be working with --debug but with --verbose for helper puppeteer.

Also, it is not showing when using npx codeceptjs run-workers even if highlightElement is true, or I am doing something wrong.

**Comment by kobenguyent** [comment]
> @kobenguyent Quick note, this seems to not be working with --debug but with --verbose for helper puppeteer.
> 
> 
> 
> Also, it is not showing when using npx codeceptjs run-workers even if highlightElement is true, or I am doing something wrong.

Hi, please check this https://github.com/codeceptjs/CodeceptJS/pull/3896

**Pull request merged**
