### PR TITLE
feat: appium v2 support

### PR DESCRIPTION
**Pull request by kobenguyent**
## Motivation/Description of the PR
- appium v2 support
- migration guide: https://github.com/codeceptjs/CodeceptJS/wiki/Migration-to-Appium-v2---CodeceptJS

Applicable helpers:
- [x] Appium

## Type of change
- [x] :fire: Breaking changes

## Checklist:
- [ ] Tests have been added
- [x] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@DavertMik

**Comment by ChetanChohan7** [comment]
@kobenguyent I was taking a look at this as it's of interest to my current work. I noticed in the appium helper file there are several instances where "browser" is misspelt as, "broswer". See lines 192 and 197 in /helper/appium.js

**Comment by xuanmai-agilityio** [comment]
@kobenguyent I also found another issue with the `_startBrowser` function, when Appium runs the 2nd test case, it will run this function and will convert the existing options to add one more `appium:` prefix in the config.
So I think we need to check and only convert it one time when the Appium starts.
So I've updated it as below and it runs smoothly. Hope this help!

Screen Shot 2023-05-09 at 10 49 59

**Comment by kobenguyent** [comment]
> @kobenguyent I also found another issue with the `_startBrowser` function, when Appium runs the 2nd test case, it will run this function and will convert the existing options to add one more `appium:` prefix in the config. So I think we need to check and only convert it one time when the Appium starts. So I've updated it as below and it runs smoothly. Hope this help!
> 
> Screen Shot 2023-05-09 at 10 49 59

Thanks @xuanmai-agilityio, issue has been addressed!

**Comment by DavertMik** [comment]
Thank you, @kobenguyent
I think we are ready to merge this one.
Sorry for the delay in reviewing it

**Review by DavertMik — APPROVED** [review]

**Pull request merged**
