### PR TITLE
Add Mobile Web Example Configurations

### PR DESCRIPTION
**Pull request by pablopaul**

### CODE REVIEW

**Comment by DavertMik** [comment]
Thanks, but this file was auto-generated from a doc-block of a JS file. Could you update `lib/helpers/Appium.js` instead? It's in the comments in the very beginning.

**Comment by pablopaul** [comment]
@DavertMik I get this wrong all the time, sorry for that, I will fix it :D

**Comment by pablopaul** [comment]
@DavertMik it is fixed now :D

**Comment by DavertMik** [comment]
Thank you!

**Pull request merged**
