### PR TITLE
revert SeleniumWebDriver init inside Protractor.js helper from commit…

### PR DESCRIPTION
**Pull request by romanovma**
… 3987de3e5145335147b713fe256fede3369e2483

#423

### CODE REVIEW

**Comment by romanovma** [comment]
Or may be we can just call
```super._init()``` 
from Protractor's _init method.
Could you check and let me know if I should update the pull request.

**Comment by DavertMik** [comment]
Sorry, could you explain how it is related to `I.pressKey` issue?

**Comment by romanovma** [comment]
Yep. Protractor helper inherits `pressKey` from SeleniumWebDriver so the following code from 'SeleniumWebdriver.js' is run:
```
pressKey(key) {
    let modifier;
    if (Array.isArray(key) && ~['Control', 'Command', 'Shift', 'Alt'].indexOf(key[0])) {
      modifier = this.webdriver.Key[key[0].toUpperCase()];
      key = key[1];
    }

    // guess special key in Selenium Webdriver list
    if (this.webdriver.Key[key.toUpperCase()]) {
      key = this.webdriver.Key[key.toUpperCase()];
    }

    let action = new this.webdriver.ActionSequence(this.browser);
    if (modifier) action.keyDown(modifier);
    action.sendKeys(key);
    if (modifier) action.keyUp(modifier);
    return action.perform();
  }
```

Once it hits any of rows with `this.webdriver.Key` it throws `Cannot read property 'Key' of undefined` which is because `this.webdriver` is `undefined`. 

Then we can see that `this.webdriver` is defined inside `SeleniumWebDrive`'s `_init` method so we can define `this.webdriver` by one of the following options: 1) doing it manually inside `Protractor`'s `_init` method (which was done before update to Protractor ver5 btw) or 2) just calling parent `_init` method which is `SeleniumWebDrive`'s `_init` method. First is more safe as I don't know the whole picture that's why I proposed it rather than the second one.

**Comment by DavertMik** [comment]
> . First is more safe as I don't know the whole picture that's why I proposed it rather than the second one.

Yes, it's more safe. I was thinking maybe a webdriver instance can also be retirived from Protractor library, but now sure, as Protractor regularely changes its API

**Comment by DavertMik** [comment]
Thanks. I think this is the best solution for now

**Pull request merged**
