### PR TITLE
Use local selenium-standalone

### PR DESCRIPTION
**Pull request by pablopaul**

### CODE REVIEW

**Comment by DavertMik** [comment]
Any reasons why selenium standalone should be local?

**Comment by pablopaul** [comment]
Yes, to be in line with latest CodeceptJS setup docs which suggests to
install codeceptjs as local node module

**Comment by DavertMik** [comment]
selenium-server-standalone is absolutely unrelated to codeceptjs package. It installs a global cli which can be used to install/update/start selenium server.
Currently, CodeceptJS do not provide any connection with this package, so you always need to start selenium manually.

**Comment by pablopaul** [comment]
OK, I close this issue.

**Pull request closed without merging**
