### PR TITLE
(feat)-Enabled the adding screenshot to failed test for moch-junit-reporter

### PR DESCRIPTION
**Pull request by PeterNgTr**
feat for this https://github.com/Codeception/CodeceptJS/issues/1502

### CODE REVIEW

**Comment by PeterNgTr** [comment]
https://github.com/michaelleeallen/mocha-junit-reporter/issues/79 Well, new version with attached screenshots is published.

**Comment by DavertMik** [comment]
Thank you!

**Comment by yogainalift** [comment]
I tried testing this feature and it did not work.
The screenshotOfFail.js correctly registers the path for the screenshot.
I believe the mocha-junit-reporter does not see the correct context. The attachment option returns the default value false and the test variable is undefined.

**Comment by PeterNgTr** [comment]
@yogainalift can you provide a sample repo, it's easier to debug and reproduce it.

**Pull request merged**
