### PR TITLE
fixed no screenshots on passed cases allure

### PR DESCRIPTION
**Pull request by PeterNgTr**
By this reported https://github.com/Codeception/CodeceptJS/issues/1494 I found out that:

- The screenshot to attach to allure for failed test cases is already handled in `screenshotOnFail.js`
```
        const allureReporter = Container.plugins('allure');
        if (allureReporter) {
          allureReporter.addAttachment('Last Seen Screenshot', fs.readFileSync(path.join(global.output_dir, fileName)), 'image/png');
        }
```

so, we don't need to handle it again in `stepByStepReport.js`
```
    const allureReporter = Container.plugins('allure');
    if (allureReporter && (step.status !== 'success')) {
      output.plugin('stepByStepReport', 'Adding screenshot to Allure');
      allureReporter.addAttachment('Screenshot', fs.readFileSync(path.join(dir, fileName)), 'image/png');
    }
```

this will lead to 
- duplicate screenshots on allure reports.
- screenshot will be added to passed cases on allure reports.

### CODE REVIEW

**Comment by DavertMik** [comment]
Ok, but If I want step-by-step reports for allure?

**Comment by PeterNgTr** [comment]
you mean, you explicitly want to add screenshots for passed cases on allure? I think that's possible if I change this abit

**Comment by PeterNgTr** [comment]
But still there are a lot of screenshots are attached to allure
screenshot 2019-02-11 at 13 57 40

**Comment by DavertMik** [comment]
Can we bring this as a config option?

**Comment by PeterNgTr** [comment]
I‘ll check it out.

**Comment by PeterNgTr** [comment]
Now when the `screenshotsForAllureReport` is set to true, you will see something like this
screenshot 2019-02-25 at 14 03 51

**Comment by DavertMik** [comment]
Thanks!

**Pull request merged**
