### PR TITLE
Within to maintain context after failure

### PR DESCRIPTION
**Pull request by imvetri**
within doesn't restore the context back to the root if the fn() execution fails because of any run time exception.

Fixed it with try catch finally block

### CODE REVIEW

**Comment by imvetri** [comment]
#457

**Comment by DavertMik** [comment]
Please remove all changes which don't belong to this PR.

**Comment by imvetri** [comment]
@DavertMik yeah thanks. that was a mistake

**Comment by imvetri** [comment]
Closing the PR as it contains irrelevant commits.

**Pull request closed without merging**
