### PR TITLE
Feature/mouse features

### PR DESCRIPTION
**Pull request by fabioel**
@DavertMik I implemented the features suggested in Issue: https://github.com/Codeception/CodeceptJS/issues/62

I did not write the tests yet, because my test runner is not working. It does not show any errors, even if I break existing tests.
Can you have a look at the `package.json` and the `gulp` file and check if everything is fine?
It would also be very great if you could add a `development` section to the `README.md`, so that it is more clear how to run tests and what to do in order to help improving `CodeceptJS`

### CODE REVIEW

**Comment by DavertMik** [comment]
I'm not fan of adding methods for pressing up and down mouse buttons, as they can't be treated as complete action. If someone needs a complex interaction, they should implement it on their own and name it accordingly. Otherwise it won't be clean what is user trying to do.

However, dragAndDrop should be added for sure. I hope you don't mind if I just copy your code (and won't merge everything else)

**Comment by gaurav21r** [comment]
@DavertMik We are testing a complex GUI drawing application and Codecept has been great so far. Unfortunately, Drag and Drop (the current API) implementation works for apps like Trello but not Drawing Tools like ours. In our case, mouseup & mousedown are actually atomic interactions for us.

Take a look at this animation:

amaze-rectangle

This can only be tested with

```
I.mousedown(x, y)
I.mousemove(x,y)
I.mouseup(x, y)
```

Requesting you to please reconsider merging this completely?

**Comment by DavertMik** [comment]
> Requesting you to please reconsider merging this completely?

Nope 😇 You won't need to have a test looking like 

```js
I.mousedown(x, y)
I.mousemove(x,y)
I.mouseup(x, y)
```
that's not useful and not readable. You will need to implement an action insidea custom helper using webdriverio API directly. This way you can customize the behavior the way you like and create an action that will fulfill your needs. 

This would look far more better:

```js
I.drawRectangle(x1,y1,x2,y2);
```

**Comment by JosueDOrtiz** [comment]
@DavertMik ,

is this still the case, not wanting mouseDown and MouseUp? Seems similar to pressKeyDown and pressKeyUp.

In my case, I am looking into ways to drag a column in a table so as to change the column order.

**Comment by storenth** [comment]
Did't understand the state of the PR. Looks like no feature provided yet.

**Pull request closed without merging**
