### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by fatih-yavuz**
fix typo on documentation `dontSeeeCheckboxIsChedcked ` to `dontSeeCheckboxIsChecked`

### CODE REVIEW

**Comment by fatih-yavuz** [comment]
> I believe the fix will be from here https://github.com/Codeception/CodeceptJS/blob/master/docs/webapi/dontSeeCheckboxIsChecked.mustache then run the npm run docs to update every where. :)

`npm run docs` triggers `gulp docs` but there is no gulpfile in the project

Full log:
```
> codeceptjs@2.3.2 docs /Users/fatih.yavuz/CodeceptJS
> gulp docs

[19:39:53] No gulpfile found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codeceptjs@2.3.2 docs: `gulp docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the codeceptjs@2.3.2 docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fatih.yavuz/.npm/_logs/2019-10-07T16_39_54_005Z-debug.log
```

**Comment by fatih-yavuz** [comment]
yes, and then, since there is no dependency to `gulp` on `package.json` I installed `gulp` globally, then tried `npm run docs` @PeterNgTr

**Comment by fatih-yavuz** [comment]
Will running the `npm run docs` not produce the same output as I did with search and replace anyways? :) If not, I am willing to run the command if you could help with the issue @PeterNgTr

**Comment by PeterNgTr** [comment]
@fatih-yavuz I'm not really sure about this part. Probably the docs generation is handled by this https://github.com/Codeception/CodeceptJS/blob/master/RoboFile.php. Your replacement with search would be fine, I think :)

**Comment by PeterNgTr** [comment]
@fatih-yavuz seems like it's the way to generate docs -> https://github.com/Codeception/CodeceptJS/pull/1952/files#diff-6a3371457528722a734f3c51d9238c13R123

**Comment by DavertMik** [comment]
yeah, sorry, instead of gulp I use [Robo](https://robo.li)
One of the reasons is that I created it :smile: Second reason - it's sync. 
But yeas, thanks for fixing this in template

**Pull request merged**
