### PR TITLE
Playwright: Added possibility of creating of a context with a page

### LINKED ISSUE #3248: Playwright: Method _startBrowser() doesn't start browser window since CodeceptJS 3.1.0
It's a regression since 3.1.0 (also 3.3.0 is affected). It works well with 3.0.7
I use similar scenario - I need to change timezone in browser and the actions "stop/start" browser are needed for it.
You can find a simple test below.

#### What are you trying to achieve?
The test passes, a page is open
#### What do you get instead?
`startBrowser()` doesn't start a browser window, therefore `I.amOnPage("/");` fails
```bash
$ codeceptjs run --verbose
context
CodeceptJS v3.3.0
Using test root "/home/mirao/workspace/codeceptjs/tests/test"
Helpers: Playwright, Common
Plugins: screenshotOnFail, retryFailedStep, tryTo

Test --
    [1]  Starting recording promises
    Timeouts: 
 › [Session] Starting singleton browser session
  Stop/start
    I stop browser 
    I start browser 
    I am on page "/"
    [1] Error | TypeError: Cannot read property 'goto' of null
    [1] Error | TypeError: Cannot read property 'goto' of null
    [1] <teardown> Stopping recording promises
 › <screenshotOnFail> Test failed, try to save a screenshot
 › Screenshot is saving to /home/mirao/workspace/codeceptjs/tests/test/output/Stop_start.failed.png
 › <TypeError: Cannot read property 'screenshot' of null> 
  ✖ FAILED in 424ms

    [2]  Starting recording promises

-- FAILURES:

  1) Test
       Stop/start:
     Cannot read property 'goto' of null
      at Playwright.amOnPage (/home/mirao/workspace/codeceptjs/node_modules/codeceptjs/lib/helper/Playwright.js:780:21)
      at Step.run (/home/mirao/workspace/codeceptjs/node_modules/codeceptjs/lib/step.js:122:47)
      at /home/mirao/workspace/codeceptjs/node_modules/codeceptjs/lib/actor.js:134:23
  
  Scenario Steps:
  - I.amOnPage("/") at Test.<anonymous> (./Test_test.js:6:7)
  - I.startBrowser() at Test.<anonymous> (./Test_test.js:5:7)
  - I.stopBrowser() at Test.<anonymous> (./Test_test.js:4:7)
```

`common_helper.js`:
```js
const Helper = require("@codeceptjs/helper");

class Common extends Helper {

    async stopBrowser() {
        return await this.helpers.Playwright._stopBrowser();
    }

    async startBrowser() {
        return await this.helpers.Playwright._startBrowser();
    }
}

module.exports = Common;
```
`Test_test.js`:
```js
Feature("Test");

Scenario("Stop/start", ({ I }) => {
    I.stopBrowser();
    I.startBrowser();
    I.amOnPage("/");
});
```

### Details

* CodeceptJS version: 3.3.0
* NodeJS Version: v14.19.0
* Operating System: Ubuntu 21.10
* Playwright 1.16.3
* Configuration file:

```js
exports.config = {
    tests: "./*_test.js",
    output: "./output",
    helpers: {
        Playwright: {
            url: "https://codecept.io",
            show: true,
            browser: "chromium"
        },
        Common: {
            require: "./common_helper.js",
        },
    },
    include: {
        I: "./steps_file.js"
    },
    bootstrap: null,
    mocha: {},
    name: "test",
    plugins: {
        pauseOnFail: {},
        retryFailedStep: {
            enabled: true
        },
        tryTo: {
            enabled: true
        },
        screenshotOnFail: {
            enabled: true
        }
    }
};

```

### PR DESCRIPTION
**Pull request by mirao**
## Motivation/Description of the PR
- I would like to be able to open page after restart of browser. I use this patch for a long time in my project and it works for me well.
- Resolves #3248

Applicable helpers:

- [ ] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [x] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] coverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] stepTimeout
- [ ] wdio
- [ ] subtitles

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [x] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [x] Tests have been added
- [x] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by DavertMik** [comment]
Thanks, seems useful
Could you add also usage documentation into https://github.com/codeceptjs/CodeceptJS/blob/3.x/docs/playwright.md

It would be also nice to have a more detailed example where you actually use `_startBrowser` and `_startContextPage`

This will help others to start using these custom methods

**Comment by mirao** [comment]
Added an example into Playwright's docs, it's my use case for `_createContextPage`

**Comment by DavertMik** [comment]
@mirao what do you think of adding restartBrowser into the Playwright helper?

Looks like it should belong there

**Comment by mirao** [comment]
@DavertMik Yes, I can add the method `restartBrowser()` into the Playwright's helper. Or should I name it `_restartBrowser()`? I'm not sure about name convention.

**Comment by DavertMik** [comment]
restartBrowser()

So user could call it natively from their tests, please update documentation accordingly to show simplified approach

**Comment by mirao** [comment]
@DavertMik Done

**Review by DavertMik — APPROVED** [review]

**Comment by DavertMik** [comment]
Thank you!
Finally we have it!

**Pull request merged**
