### PR TITLE
fix for expected type of "bootstrap", "teardown", "bootstrapAll" and "teardownAll"

### PR DESCRIPTION
**Pull request by ngraf**
…"teardownAll"

## Motivation/Description of the PR
- Fixes Typescript type of "bootstrap", "teardown", "bootstrapAll" and "teardownAll"
- Resolves issue reported in Slack: https://codeceptjs.slack.com/archives/C94G8JXJB/p1664174040678089

> Souvik Dutta
> Hi All, I am trying to configure bootstrap with TS and it gives me following error, any idea why this is happening

## Type of change

- [ x ] :bug: Bug fix

## Checklist:

- [ ] Tests have been added
- [ x ] Documentation has been added (Run `npm run docs`)
- [ x ] Lint checking (Run `npm run lint`)
- [ x ] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by kobenguyent** [comment]
hi @ngraf please rebase with 3.x branch if you can spare some time to make the failed tests green again 😸

**Comment by ngraf** [comment]
Hi @PeterNgTr ,
I rebased my branch with 3x. branch as you said. 
Still there is a (flaky?) unit test failing for "Timeout" feature. I am quite confident that because of the nature of my changes that my changes are not the cause of the fails. I don't think I am good enough with the framework to fix those flaky tests within my PR.

**Comment by kobenguyent** [comment]
Hi @ngraf it happens intermittently. I'm not sure why but I guess, increasing the timeout may help.

**Review by DavertMik — APPROVED** [review]

**Comment by DavertMik** [comment]
Thanks!

**Pull request merged**
