### PR TITLE
Document re-org

### PR DESCRIPTION
**Pull request by xt1**
Split quickstarts into own documents.
Moved a bunch of stuff into 'Concepts'.
Moved other things around.
Removed done() footers.

### CODE REVIEW

**Comment by xt1** [comment]
Preview at http://xt1.org/codecept/

**Comment by DavertMik** [comment]
Thank you!
As you noticed I restructured documentation on site as well and also I have moved everything to nicer looking docusaurus website from mkdocs. However, this switch has its own issues: docusaurus doesn't support dropdown menus so I can't have the structure you proposed.

I like the new guides. I know we need more pages of such like "Drag & Drop" to fulfill issues like picking values in custom selects, calendars, sliders, etc. 

However, in the proposed structure, there are too much information linked. It's really hard to keep everything simple when you don't even know which dropdown menu should I click :) For instance, it's not a Quickstart when you stumble upon selecting the right quickstart menu item )

On the new website I have only Guides and Reference. I think everything can belong to one of those categories. 

So I will merge your changes but I need to think about how to make it fit into the new structure.

**Comment by xt1** [comment]
Oh don't worry about merging this PR if it doesn't fit with your new
structure.

Might be easier to start over with the new structure.

Documentation falls into 4 types:
- quickstarts: give an overview
- concepts: theory
- guides: task specific
- reference: details

I think a new PR focusing on improving the quickstarts with a better
example is maybe more useful than this one.

I find this to be a useful read on documentation structure

https://www.divio.com/blog/documentation/

TUTORIALS
A tutorial:

is learning-oriented
allows the newcomer to get started
is a lesson
Analogy: teaching a small child how to cook

HOW-TO GUIDES
A how-to guide:

is goal-oriented
shows how to solve a specific problem
is a series of steps
Analogy: a recipe in a cookery book

EXPLANATION
An explanation:

is understanding-oriented
explains
provides background and context
Analogy: an article on culinary social history

REFERENCE
A reference guide:

is information-oriented
describes the machinery
is accurate and complete
Analogy: a reference encyclopaedia article

**Comment by DavertMik** [comment]
I will try to pick the best parts and put it into the new structure. 
So don't worry, I will keep your work and try to make it the part of the site

**Comment by DavertMik** [comment]
I'm sorry to close this but documentation went far forward from this commit.
If there are still missing parts or parts that can be improved, add them one by one into corresponding guides.

Thank you!

**Pull request closed without merging**
