### PR TITLE
waitWhileElement

### PR DESCRIPTION
**Pull request by sabau**
Hi, 
as described in the issue [waitWhileElement](https://github.com/Codeception/CodeceptJS/issues/682) I was trying to replicate a feature I was used to. I hope to have covered everything from helpers to docs update to tests coverage.

I hope it can be a useful feature. I often have to wait random amount of time due to slow DB, high loads, different environments to be tested, usually some graphical elements disappears (modals or spinner).

Best regards,
Karoly

### CODE REVIEW

**Comment by DavertMik** [comment]
Thanks, for the comprehensive implementation and tests
However, I don't find the naming really good. Wait whileElement sounds to abstract to me, I'd never guess what it waits for before I go to docs. I think it should be much more descriptive. How about 
`waitToDisappear` or `waitForElementToDisappear`? Maybe you could have another good ideas? 

Also please fix the SeleniumWebdriver implementation. Thanks

**Comment by sabau** [comment]
True, is just took it as it was. Disappear maybe can be confused with the concept of visibility, what about `waitForElementRemoval` or `waitUntilElementRemoved`?

Sorry, I missed that SeleniumWebdriver bug, I'll fix it as soon as I can.

**Comment by APshenkin** [comment]
@sabau @DavertMik There is already implementation for WebdriverIO - `waitForInvisible` and `waitForStalenessOf`
I think we can use this names for methods

**Comment by sabau** [comment]
Hi @APshenkin, 
I was looking at them, they are very similar, I think the main differences are:

- `waitForStalenessOf` is expecting the element to be present and disappear after a while, but we can't be sure everytime that the element is there.
- `waitForInvisible` is satisfied both when all elements are removed or when all elements become invisible, it covers this new call, but have a wider scope.

But looking at WebdriverIO/jquery I was missing the classical name `waitUntilExists`

**Comment by DavertMik** [comment]
Yes, `waitUntilExists` looks better to me

**Comment by sabau** [comment]
Hi @DavertMik, sorry for the long waiting. 
Ok, then I'll fix the naming ASAP, hopefully today.

**Comment by DavertMik** [comment]
Thank you!

**Pull request merged**
