### PR TITLE
do not throw error in dispatcher

### PR DESCRIPTION
**Pull request by Zougi**
fix issue https://github.com/Codeception/CodeceptJS/issues/262

### CODE REVIEW

**Comment by Zougi** [comment]
this is not enough, because error is not catch, we should add `.on('error', callback)` on error dispatcher

**Comment by Zougi** [comment]
ideally we should send error from dispatcher (see what I did initially in my first commit), then we should listen to the error in the file we first use lib/event (that would be codecept,js!?) and log the error from there, not in lib/event itself

**Comment by Zougi** [comment]
my third commit is to catch fail event gotten from mocha. without this, process do not exit even if all tests finished

**Comment by DavertMik** [comment]
Thanks for the report and fix. Yeah, I have failures in examples just to demonstrate that things actually are executed and actually test what they should. Thanks for noticing that hanging

**Comment by DavertMik** [comment]
Looks like Yahoo page changed and it started to fail in Nightmare...

**Pull request merged**
