### PR TITLE
Fix for grabNumberOfVisibleElements, fixes #1081

### LINKED ISSUE #1081: [Nightmare] grabNumberOfVisibleElements - return undefined
#### What are you trying to achieve?
Method **grabNumberOfVisibleElements** must be return number visible elements

#### What do you get instead?
undefined

> Provide console output if related. Use `--verbose` mode for more details.

```bash
   Emitted | step.passed (I am on page "/")
   Step finished in 2.514 sec
   Emitted | step.finish (I am on page "/")
   Emitted | step.start (I grab number of visible elements "[data-qa=SearchBox-searchButton]")
 • I grab number of visible elements "[data-qa=SearchBox-searchButton]"
   Emitted | step.passed (I grab number of visible elements "[data-qa=SearchBox-searchButton]")
   Step finished in 30.034 sec
   Emitted | step.finish (I grab number of visible elements "[data-qa=SearchBox-searchButton]")
undefined
   Emitted | test.passed ([object Object])
   Emitted | test.finish ([object Object])
 ✓ OK in 32553ms

   Emitted | test.after ([object Object])
  [Session] cleaning up

```

> Provide test source code if related

```js
//example_test.js
Feature('Example');

Scenario('test something', async (I) => {
    I.amOnPage('/')
    let a = await I.grabNumberOfVisibleElements('[data-qa=SearchBox-searchButton]')
    console.log(a)
});
```

### Details

* CodeceptJS version: v1.2.1
* NodeJS Version: v9.6.1
* Operating System: MacOS 10.13.4 
* codeceptjs-nightmare@1.1.0 | nightmare@3.0.1
* Configuration file:

```js
{
  "tests": "./*_test.js",
  "timeout": 10000,
  "output": "./output",
  "helpers": {
    "Nightmare": {
      "url": "http://anysite.com",
      "show": true,
      "restart": false,
      "windowSize": "1920x1080"
    }
  },
  "include": {
    "I": "./steps_file.js"
  },
  "bootstrap": false,
  "mocha": {},
  "name": "CodeceptJs"
}
```

### PR DESCRIPTION
**Pull request by stefanschenk**
Based on analysis on slack channel, method for grabNumberOfVisibleElements now reflects methodology as used by seeElement. Als mention for Jinbo Jinboson for looking into this issue.

### CODE REVIEW

**Comment by DavertMik** [comment]
Please fix formatting issues. 
Also It would be perfect if you could add some test for this case. 

Check https://github.com/Codeception/CodeceptJS/blob/master/test/helper/webapi.js

**Comment by jehord** [comment]
Very need this fix

**Comment by stefanschenk** [comment]
One of my added tests for grabNumberOfVisibleElements fails for ProtractorWeb tests. Apparently the method isDisplayed used by protractor sees elements with `style='display: none'` as visible

**Comment by stefanschenk** [comment]
@DavertMik Travis CI build was terminated for one test. Can you look?

**Comment by DavertMik** [comment]
Yes. thanks!

**Pull request merged**
