### PR TITLE
[feature] Enable overriding of `config.tests` for `run-multiple`

### PR DESCRIPTION
**Pull request by sveneisenschmidt**
See #978

### CODE REVIEW

**Comment by sveneisenschmidt** [comment]
@DavertMik @reubenmiller Sempahore CI build failed, can you have a look please? 💐

**Comment by reubenmiller** [comment]
@sveneisenschmidt I'm looking into this now

**Comment by sveneisenschmidt** [comment]
@reubenmiller Thanks for looking into it. What was the issue at the end?
(Still want me to invite to the Slack group?)

**Comment by reubenmiller** [comment]
@sveneisenschmidt The sephamore tests are a little flaky. The build failed before because of some issue when running `npm install`...then I just restarted the build and it was fixed :/ I think i'll have to look into sometime.

Yeah I think we can add you to the slack dev channel (and I think I have the right permissions to do so). What's your slack username?

**Comment by sveneisenschmidt** [comment]
@reubenmiller Thanks for the exolaination. About slack, I think you need to invite me to your workspace/channel via my mail: `sven.eisenschmidt[at]gmail[dot]com`.

**Comment by reubenmiller** [comment]
@sveneisenschmidt yep, finally found the link.

**Comment by sveneisenschmidt** [comment]
@reubenmiller Worked, I'm in. Thank you :)

**Comment by DavertMik** [comment]
Done!

**Pull request merged**
