### PR TITLE
[feature] Enable glob patterns in `config.test` / `Codecept.loadTests`

### PR DESCRIPTION
**Pull request by sveneisenschmidt**
See #976

### CODE REVIEW

**Comment by reubenmiller** [comment]
Great work :) Though can you please fix the linting issues because it is causing the ci tests to fail.

**Comment by sveneisenschmidt** [comment]
@DavertMik @reubenmiller  `Hound` and `Codacy` seems to have a different opinion here. Any idea how to fix this? I use the default .editorconfig and the file just looks fine.

**Comment by reubenmiller** [comment]
@sveneisenschmidt what do you get when you run the linting locally? `npm run lint`. If it fails there then you might be able to use `npm run lint-fix`.

Though it's strange because in the travis tests, it runs `npm run lint` and I've already seen that the tests are passing (so that would suggest the above commands are working fine).

**Comment by sveneisenschmidt** [comment]
@reubenmiller Yep, seems all good:

```console
> docker run -i -t --rm -v $PWD:/data:cached -w /data node:9 /bin/bash
root@c981a7f8eb1e:/data# npm install
added 136 packages and updated 1 package in 92.467s

root@c981a7f8eb1e:/data# npm run lint
> codeceptjs@1.1.6 lint /data
> eslint bin/ examples/ lib/ test/ translations/

root@c981a7f8eb1e:/data# npm run lint-fix
> codeceptjs@1.1.6 lint-fix /data
> eslint bin/ examples/ lib/ test/ translations/ --fix

root@c981a7f8eb1e:/data
```

How to proceed now? :)

**Comment by DavertMik** [comment]
I'm still pretty not sure what to use .hound or codacy so I'm keeping both to look who serves better :)
Anyway, this is not that important, everything can be fixed with fixing lint.
So I'm nerging this PR too

**Pull request merged**
