### PR TITLE
fix: Puppeteer helper doc broken link

### PR DESCRIPTION
**Pull request by yoannfleurydev**
## Motivation/Description of the PR

- Description of this PR, which problem it solves

Broken link in puppeteer helper documentation

Applicable helpers:

- [ ] Playwright
- [ ] Puppeteer
- [ ] WebDriver
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] TestCafe

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] coverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] stepTimeout
- [ ] wdio
- [ ] subtitles

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [ ] :bug: Bug fix
- [ ] 🧹 Chore
- [x] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Review by kobenguyent — CHANGES_REQUESTED** [review]
As the .md  files are taken care by `npm run docs`

so please update here
https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/helper/Puppeteer.js#L2475
https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/helper/Puppeteer.js#L2480

then run `npm run docs` to update the documentations.

**Comment by yoannfleurydev** [comment]
@kobenguyent there is an issue while running `npm run docs`.

image

I installed dependencies (using `--force`) with Node.js 18 and Node.js 20 because it was not installing dependencies (https://github.com/codeceptjs/CodeceptJS/issues/4371)

**Comment by kobenguyent** [comment]
Could you try this npm run def && npm run docs

**Comment by yoannfleurydev** [comment]
`npm run def` is giving me an error.

```
[#35 NPX] › ℹ  npx documentation build lib/plugin/*.js -o docs/plugins.md -f md --shallow --markdown-toc=false --sort-order=alpha
Building @codecepjs/detox helper docs
[#36 REPLACEINFILE] › ℹ  node_modules/@codeceptjs/detox-helper/Detox.js
[#36 REPLACEINFILE] › ✖  Failed with "ENOENT: no such file or directory, open 'node_modules/@codeceptjs/detox-helper/Detox.js'"  in 0 ms
[#36 REPLACEINFILE] › ⚠  warning   Execution stopped
```

And then running `npm run docs` is kind of giving me the same one.

```
> codeceptjs@3.6.2 docs
> ./runok.js docs

Writing documentation for AI
[#1 COPY] › ℹ  lib/helper/AI.js => docs/build/AI.js
[#1 COPY] › ✔  Finished  in 1 ms
[#2 REPLACEINFILE] › ℹ  docs/build/AI.js
[#2 REPLACEINFILE] › ✔  Finished  in 0 ms
[#3 NPX] › ℹ  npx documentation build docs/build/AI.js -o docs/helpers/AI.md -f md --shallow --markdown-toc=false --sort-order=alpha
[#4 NPX] › ℹ  npx documentation build lib/plugin/*.js -o docs/plugins.md -f md --shallow --markdown-toc=false --sort-order=alpha
Building @codecepjs/detox helper docs
[#5 REPLACEINFILE] › ℹ  node_modules/@codeceptjs/detox-helper/Detox.js
[#5 REPLACEINFILE] › ✖  Failed with "ENOENT: no such file or directory, open 'node_modules/@codeceptjs/detox-helper/Detox.js'"  in 0 ms
[#5 REPLACEINFILE] › ⚠  warning   Execution stopped
```

**Comment by kobenguyent** [comment]
> `npm run def` is giving me an error.
> 
> ```
> [#35 NPX] › ℹ  npx documentation build lib/plugin/*.js -o docs/plugins.md -f md --shallow --markdown-toc=false --sort-order=alpha
> Building @codecepjs/detox helper docs
> [#36 REPLACEINFILE] › ℹ  node_modules/@codeceptjs/detox-helper/Detox.js
> [#36 REPLACEINFILE] › ✖  Failed with "ENOENT: no such file or directory, open 'node_modules/@codeceptjs/detox-helper/Detox.js'"  in 0 ms
> [#36 REPLACEINFILE] › ⚠  warning   Execution stopped
> ```
> 
> And then running `npm run docs` is kind of giving me the same one.
> 
> ```
> > codeceptjs@3.6.2 docs
> > ./runok.js docs
> 
> Writing documentation for AI
> [#1 COPY] › ℹ  lib/helper/AI.js => docs/build/AI.js
> [#1 COPY] › ✔  Finished  in 1 ms
> [#2 REPLACEINFILE] › ℹ  docs/build/AI.js
> [#2 REPLACEINFILE] › ✔  Finished  in 0 ms
> [#3 NPX] › ℹ  npx documentation build docs/build/AI.js -o docs/helpers/AI.md -f md --shallow --markdown-toc=false --sort-order=alpha
> [#4 NPX] › ℹ  npx documentation build lib/plugin/*.js -o docs/plugins.md -f md --shallow --markdown-toc=false --sort-order=alpha
> Building @codecepjs/detox helper docs
> [#5 REPLACEINFILE] › ℹ  node_modules/@codeceptjs/detox-helper/Detox.js
> [#5 REPLACEINFILE] › ✖  Failed with "ENOENT: no such file or directory, open 'node_modules/@codeceptjs/detox-helper/Detox.js'"  in 0 ms
> [#5 REPLACEINFILE] › ⚠  warning   Execution stopped
> ```

well, I think you haven't run `npm i -f`

**Review by kobenguyent — APPROVED** [review]

**Comment by yoannfleurydev** [comment]
Thanks a lot, I removed my `node_modules` and did again install force, and it worked.

The PR is updated with your feedbacks. Thanks a lot for your patience and answering my dumb questions 😄

**Comment by kobenguyent** [comment]
No worries @yoannfleurydev 😀 I bumped into the same thing when I first touched the codebase.

**Pull request merged**
