### PR TITLE
Send non-nested array of files to custom parallel execution chunking function.

### PR DESCRIPTION
**Pull request by mikecbrant**
Currently, an (unexpected?) array wrapper is applied to the array of files being passed to the parallel execution custom file chunking function.  I would think expected behavior here is just getting the array of files as noted in online documentation.

This might need to be considered a breaking change depending on how users are currently using this functionality.

### CODE REVIEW

**Comment by DavertMik** [comment]
@sveneisenschmidt any ideas?

**Comment by sveneisenschmidt** [comment]
@DavertMik That's the fix we need. All correct.

**Comment by DavertMik** [comment]
Thanks!

**Comment by mikecbrant** [comment]
The custom function is shown below. All I am trying to achieve is to execute all test files in parallel, which might seem to be something that ought to be an available option.

```
    multiple: {
        parallel: {
            chunks: (files) => {
                return files[0].reduce(
                    (arr, file) => {
                        arr.push([ file ]);
                        return arr;
                    },
                    []
                );
            },
            browsers: ['Nightmare']
        }
    }
```

A tangential question as working with parallel execution.  Are there any reporting set-ups you might recommend here?  Finding the interleaving of stdout to terminal making it hard to see consolidated result report at the end.

**Pull request merged**
