### PR TITLE
Add in loading config from a JS file

### PR DESCRIPTION
**Pull request by smozely**
Make it easier to configure CodeceptJS
- Not include keys in config files / source control
- Run on different browsers via env flags

RE Issue #59

### CODE REVIEW

**Comment by DavertMik** [comment]
Thank you! 

> Run on different browsers via env flags

Btw, could you explain how to use env flags?

**Comment by smozely** [comment]
@DavertMik your onto them quick today :smile:

For using env settings ... with this I can write my codecept.js config file like this ...

```
exports.config = {
  helpers: {
    WebDriverIO: {
      url: process.env.url, 

... more configs ...
```

I can then run 
```url=https://beta.example.com codeceptjs run --steps```

To control what url the tests run against, good for switching between localhost, test, prod ... same logic applies to the keys for things like sauce labs. Even going to use it to control running our test suite against multiple Browser/OS combinations.

**Comment by smozely** [comment]
Im lost as to why the build is breaking, my changes should have no effect if you don't have a codecept.js file sitting where the config lives

**Comment by DavertMik** [comment]
> Im lost as to why the build is breaking, my changes should have no effect if you don't have a codecept.js file sitting where the config lives

Looks like it was Travis issue

**Comment by DavertMik** [comment]
> To control what url the tests run against, good for switching between localhost, test, prod ... same logic applies to the keys for things like sauce labs. Even going to use it to control running our test suite against multiple Browser/OS combinations.

Ok, that makes sense. I think I should mention this in documentation

**Pull request merged**
