### PR TITLE
Fix for #889 - Checking if console.log was called with array or not

### PR DESCRIPTION
**Pull request by KennyRules**

### CODE REVIEW

**Comment by DavertMik** [comment]
What if an object was passed in? 
Maybe just convert it to JSON?

**Comment by KennyRules** [comment]
Hm, I'm not seeing this comment on GitHub, so gonna respond via email!

For this situation, if a JSON object is passed, it would need to be handled
further down the chain.

According to the Puppeteer docs, args can only be an array of JSHandles for
the console callback:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-consolemessage

Unless there is something I missed?

**Comment by KennyRules** [comment]
@DavertMik : After some trial-and-error, I found a potential way to resolve the Semaphore error!

If you think it's a good idea, I can open another PR to replace npm with yarn to keep this PR focused on the bugfix.

Alternatively, or perhaps additionally, there might be some Semaphore project settings that could be tweaked? I'm not familiar with the tool, though it seems that it can only be changed on the project page.

**Comment by DavertMik** [comment]
> Hm, I'm not seeing this comment on GitHub, so gonna respond via email!

Yeah, I understood the way it works and deleted my comment. Sorry )

>  I can open another PR to replace npm with yarn to keep this PR focused on the bugfix.

I think both yarn lock and package lock should be removed from the repo. Anyway, they won't be taken into account when installed as a library and better to keep them out

**Pull request merged**
