### PR TITLE
[Invalid PR] Fix sorting in retries array

### PR DESCRIPTION
**Pull request by abhimanyupandian**
## Motivation/Description of the PR
When a retry is added to the global retires within recorder.add the retries are sorted based on the availability of the when fn. The sort logic is currently returning a boolean but it must return a -1 or 1 for sorting to occur currently. This PR fixes this.

Applicable helpers:

- [ ] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [ ] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] coverage
- [x] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] stepTimeout
- [ ] wdio
- [ ] subtitles

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [x] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by abhimanyupandian** [comment]
@DavertMik could you please review and merge this bug fix?
The UTs are failing due to someother reason and not due to the changes in this fix.

**Comment by DavertMik** [comment]
@abhimanyupandian I'm a bit afraid to merge any change into recorder. 
Could you explain me the issue you have hit to ensure this PR solves it. Thanks
Maybe it is possible to have unit test for this case?

**Comment by abhimanyupandian** [comment]
> @abhimanyupandian I'm a bit afraid to merge any change into recorder. Could you explain me the issue you have hit to ensure this PR solves it. Thanks Maybe it is possible to have unit test for this case?

Please find my response here https://github.com/codeceptjs/CodeceptJS/pull/3234/commits/3efd777da49028bfdca7d35b565fb46a5087697c

**Comment by abhimanyupandian** [comment]
@DavertMik screwed something up as part of the commits :(
Please confirm if this PR can be deleted, will raise a support ticket for the same.

**Pull request closed without merging**
