### PR TITLE
Feat/test rail integration

### PR DESCRIPTION
**Pull request by PeterNgTr**
I think people are currently interested in how we could send test results to testrail once the tests are executed by codeceptjs (https://codecept.discourse.group/t/testrail-plugin/36). This one will basically fulfill this. 

Test run will be created and push test results to test cases. Currently, there are just following statuses
- passed
- failed

Other statuses are not currently supporting by codeceptjs events.

### CODE REVIEW

**Comment by DavertMik** [comment]
Yeah, I have such concern as well. 
TestRail is cool but it adds a dependency and I don't know if it's a good idea to take it into the core. I think it should be a standalone package and it can be listed somewhere on a site or in our discourse group. Anyway, we need a better home for 3rd party plugins.

**Comment by DavertMik** [comment]
@PeterNgTr 
Please create a standalone package. Add it to the list of community helpers https://github.com/Codeception/CodeceptJS/wiki/Community-Helpers

On the new website there is a link to that page so everyone can search for community helpers. 
So if you add it there it won't be lost :smiley:

**Comment by PeterNgTr** [comment]
Thanks, I’ll do it

**Comment by PeterNgTr** [comment]
Added to suggested page :)

**Pull request closed without merging**
