### PR TITLE
check if browser is W3C instead of Android

### PR DESCRIPTION
**Pull request by mikk150**
## Motivation/Description of the PR
My first implementation to this was stupid, this is way better one
- Resolves #3317

Applicable helpers:

- [x] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [ ] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] coverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] stepTimeout
- [ ] wdio
- [ ] subtitles

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [ ] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [x] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by kobenguyent** [comment]
Hi @mikk150 so this check would be sufficient for both android and iOS right? Just out of curiosity.

**Comment by mikk150** [comment]
> Hi @mikk150 so this check would be sufficient for both android and iOS right? Just out of curiosity.

if webdriverio reports iOS as W3C browser(Which it should, because it is really Appium), then I do not see why not

**Review by Arhell — APPROVED** [review]

**Comment by DavertMik** [comment]
Thanks!

**Comment by mjalav** [comment]
I did check this change with codeceptjs v3.6.7 and seems it's not working. I have native android app and when I open the app and check  "this.browser.isW3C" it's false and "this.browser.isMobile" is true. base on new condition it will do touchClick which gave me error:
ERROR webdriver: WebDriverError: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource when running "touch/click" with method "POST" and args "{"element":"00000000-0000-010f-ffff-ffff00000031"}"

I reverted your code changes locally and I see it perform element click action which pass my test. 

My question is about how "this.browser.isW3C" should drive a decision for touchClick or elementClick. seems like unrelated and make error.
Would you please reconsider this change?
(Fail) New changes:     const clickMethod = this.browser.isMobile && !this.browser.isW3C ? 'touchClick' : 'elementClick';
(pass) Old changes:   const clickMethod = this.browser.isMobile && this.browser.capabilities.platformName !== 'android' ? 'touchClick' : 'elementClick';

**Pull request merged**
