### PR TITLE
[Playwright] add support for custom locators in findElements

### PR DESCRIPTION
**Pull request by Georgegriff**
## Motivation/Description of the PR
- Support custom locators in find elements for Playwright.
- Ultimately this is steps towards enabling a plugin I am working on for shadow dom support.

Context: https://github.com/Georgegriff/query-selector-shadow-dom/pull/27

Copied this from corresponding example in `waitForElement` 

Applicable helpers:

- [ ] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [x] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] puppeteerCoverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] wdio

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [ ] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by DavertMik** [comment]
I restared CI builds

**Comment by Georgegriff** [comment]
Looks like my change caused some test failures will take a look as soon as I get chance

**Comment by Georgegriff** [comment]
I also have https://github.com/Codeception/CodeceptJS/pull/2277/files which builds on this PR but those changes require a playwright to release changes to their lib. FYI they have changed the API for waitForSelector `visibility` is becoming `waitFor`

**Comment by DavertMik** [comment]
@Georgegriff at the same very moment we are introducing shadow dom support to WebDriver helper. Please could you join the discussion here #2276? We are discussing syntax for Web Component locators. And we should have some solution that is unified to both.

**Comment by DavertMik** [comment]
Also if possible, please combine this PR with #2277

**Comment by Georgegriff** [comment]
Closing in favour of other or above

**Pull request closed without merging**
