### PR TITLE
(enh): Introduce yaml config file for semaphore 2.0

### PR DESCRIPTION
**Pull request by PeterNgTr**
## Motivation/Description of the PR
- Providing semaphore yml

### CODE REVIEW

**Comment by PeterNgTr** [comment]
I checked this on my fork, the tests are triggered. Basically, it needs @DavertMik to convert the semaphore to v2.0 and add the saucelabs creds.

**Comment by PeterNgTr** [comment]
@pablopaul it’s the semaphore 2.0, they introduced the yml config file.

**Comment by pablopaul** [comment]
@PeterNgTr do we already use Semaphore v1?

**Comment by PeterNgTr** [comment]
> @PeterNgTr do we already use Semaphore v1?

yeah, the current is semaphore v1

**Pull request merged**
