### PR TITLE
fixed test-retries reports with run-workers

### LINKED ISSUE #1985: Feature Level Retires not being correctly reported with run-workers
#### What are you trying to achieve?
We have some flaky tests that we use the retry function in CodeceptJS for, and it looks like when we run the tests with run-workers and a test fails, but then passes on the retry, the failure is reported and the test fun fails completely.

#### What do you get instead?
When a retry is executed and subsequently passes, the run should succeed 

### Details

* CodeceptJS version: 2.3.3
* NodeJS Version:v12.4.0
* Operating System:Alpine Linux
* WebDriverIO: 5.15.1

### PR DESCRIPTION
**Pull request by Nizarius**
## Motivation/Description of the PR

Fixes #1985

## Type of change

- [x] Bug fix

## Checklist:
- [x] Tests have been added
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by DavertMik** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- test/data/sandbox/workers/retry_test.worker.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DavertMik/CodeceptJS/pullRequest?prid=4843657&bid=16079230)

**Comment by koushikmohan1996** [comment]
#2141  Will fix this issue

**Comment by Nizarius** [comment]
> #2141 Will fix this issue

Oh, didn't see your PR. Do you need any help with that?

**Comment by koushikmohan1996** [comment]
> Oh, didn't see your PR. Do you need any help with that?
Well, you can review PR :)

**Comment by DavertMik** [comment]
Closed in favor of #2141

**Pull request closed without merging**
