### PR TITLE
Add support for webdriver.io timeouts

### PR DESCRIPTION
**Pull request by easternbloc**
This adds support for each possible timeouts option in webdriver.io

In your codecept.conf.js you can express it something like:

```
{
  ...
  WebDriverIO: {
    url: 'http://localhost:8080',
    browser: 'phantomjs',
    timeouts: {
      implicit: 10000,
     'page load': 20000
      script: 5000
    }
  }
}
```

### CODE REVIEW

**Comment by DavertMik** [comment]
Wow, thanks. Those options should be documented as well, I think I can do it.

**Comment by easternbloc** [comment]
thanks!

**Comment by DavertMik** [comment]
I think this should options should be defined per tests, as well. Or inside the code...
It would be useful to define special timeout settings before some heavy pages or data to be loaded

**Comment by easternbloc** [comment]
@DavertMik yeah although I think some of the timeouts once set run for the duration of the webdriver instance so not quite sure how that'd play out...

**Comment by DavertMik** [comment]
Probably we need more methods to be added to do this, like:

```
I.defineTimeouts({ script: 5000 });
```

**Comment by DavertMik** [comment]
better to call this function another way for not to be confused with real `setTimeout` ;)

**Pull request merged**
