### PR TITLE
proxy pass

### PR DESCRIPTION
**Pull request by dmred**
added proxy pass to rest helper
very needed and useful for QAs and pentesters

### CODE REVIEW

**Comment by dmred** [comment]
I can't understand, I've just edited REST helper, why are there any problems with Protractor???

**Comment by LukoyanovE** [comment]
> I can't understand, I've just edited REST helper, why are there any problems with Protractor???

I see same error for protractor and webdriver in my and some others PRs.
Looks like a some dependency problem

**Comment by DavertMik** [comment]
Yeah, Protractor stuff is some unrelated and probably it's something with Travis CI.

However, could you pass the proxy stuff inside a config of REST helper?
I don't think that everyone would love to include proxy config on each request

**Comment by dmred** [comment]
> Yeah, Protractor stuff is some unrelated and probably it's something with Travis CI.
> 
> However, could you pass the proxy stuff inside a config of REST helper?
> I don't think that everyone would love to include proxy config on each request

so, I've added by default turned it off, but having ability to change proxy in *_test.js can help us if we need to change proxy lots of times while testing(or parsing) specific APIs

Well, i think the compromise is to add it to HELPER config and to the third param by default turned off

**Comment by DavertMik** [comment]
>  and to the third param by default turned off

I am really against specifying configuration inside a test file itself. 
Case of switching between proxy servers is pretty rare so I'd like not to introduce a new parameter just for it, as we may need it for something else...  

I think you should write a custom helper which allows different proxy configs:

```js
MyHelper: {
  require: './my_helper',
  proxies: {
    server1: {}, // server config
    server2: {}
  }
}
```
Then inside the helper you can change configuration for REST:

```js
// inside a helper
function changeProxy(name)
  this.helpers.REST._setConfig({ proxy: this.config.proxies[name] });
}
```
Is the idea clear?

**Comment by DavertMik** [comment]
No activity, closing

**Pull request closed without merging**
