### PR TITLE
feat(run-workers) : Add support of multiple browsers for run-workers

### PR DESCRIPTION
**Pull request by karanshah-browserstack**
## Motivation/Description of the PR
- Adding Support of using multiple with run-workers to run multiple browsers out of the box with workers instead of triggering it by manually creating a custom runner.

## Type of change

- [x] :rocket: New functionality

## Checklist:

- [x] Tests have been added
- [x] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@DavertMik

**Comment by karanshah-browserstack** [comment]
@Arhell @DavertMik Do we have any update on this?

**Comment by karanshah-browserstack** [comment]
@Arhell @DavertMik Do we have any update on this?

**Comment by karanshah-browserstack** [comment]
@Arhell @DavertMik Do we have any update on this?

**Review by DavertMik — APPROVED** [review]
Thanks, seems like a useful feature. Sorry for the delay reviewing it. I am going to merge it soon and make a release

**Review by DavertMik — APPROVED** [review]
Seems like the best of two worlds, run-multiple and run-workers

Thank you so much for this awesome feature!

**Pull request merged**
