### PR TITLE
Reinstate typescript generation for custom steps

### PR DESCRIPTION
**Pull request by xt1**
generates TS declarations for custom steps (like login(user,pass) ) and say(msg).

### CODE REVIEW

**Comment by DavertMik** [comment]
Nice! Do you think it would be possible to add TS definitions to page objects as well? 
That would be really helpful

**Comment by xt1** [comment]
I will see what I can do about page objects - need to become a bit more familiar with the guts of the system. Back on monday.

I guess each page object needs an interface in the steps.d.ts file.

**Comment by DavertMik** [comment]
> I guess each page object needs an interface in the steps.d.ts file.

Yeah, I think it as well. I didn't get any further as I didn't have enough time for that. But that's what really needs to be done.

Here is what you can use:

```js
container.support() // returns all support objects: PageObjects and actor
```

you can go through them and get all methods out of them

**Comment by xt1** [comment]
Now generates page object interfaces and adds placeholders to the callback signature.

```js
type ICodeceptCallback = (i: CodeceptJS.I, aPage:any, anotherPage:any) => void;


declare namespace CodeceptJS {
  export interface I {
    amOutsideAngularApp() : void,
    amInsideAngularApp() : void,
    amOnPage(url: string) : void,
// ... etc
   say(msg: string) : void,
    retryStep(opts: string) : void,
  }

  export interface aPage {
    send_a_Form(email: string, password: string) : void,
  }

  export interface anotherPage {
    sendForm(email: string, password: string) : void,
    bing(words: string) : void,
    bong() : void,
  }
}
```

**Comment by xt1** [comment]
Ready to merge.

**Comment by DavertMik** [comment]
Thanks!

**Pull request merged**
