### PR TITLE
Bump eslint from v8 to v9

### PR DESCRIPTION
**Pull request by thomashohn**
## Motivation/Description of the PR
- Dump eslint from v8 to v9
- Resolves 4590

Applicable helpers:

- [ ] Playwright
- [ ] Puppeteer
- [ ] WebDriver
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] TestCafe

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] coverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] stepTimeout
- [ ] wdio
- [ ] subtitles

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [ ] :bug: Bug fix
- [x] 🧹 Chore
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by thomashohn** [comment]
@kobenguyent - not sure why the typing tests are failing because of the eslint upgrade ? Seems unrelated or?

**Comment by kobenguyent** [comment]
> @kobenguyent - not sure why the typing tests are failing because of the eslint upgrade ? Seems unrelated or?

missing args?
```
  typings/promiseBasedTypes.d.ts:367:8
  ✖  367:8  Property runInWeb in type AppiumTs is not assignable to the same property in base type WebDriverTs.
  Type (fn: any) => Promise<any> is not assignable to type () => Promise<any>.
    Target signature provides too few arguments. Expected 1 or more, but got 0.  

  typings/types.d.ts:367:8
  ✖  367:8  Property runInWeb in type Appium is not assignable to the same property in base type WebDriver.
  Type (fn: any) => void is not assignable to type () => void.
    Target signature provides too few arguments. Expected 1 or more, but got 0.                      

  2 errors
```

**Comment by thomashohn** [comment]
But from what are the files generated? Seem to be my problem

**Comment by kobenguyent** [comment]
sounds like the issue is here https://github.com/codeceptjs/CodeceptJS/blob/cac15730474bca9ba7e645f56837e68a003410ae/lib/helper/Appium.js#L497
the function provides param but the typing is not.

**Comment by thomashohn** [comment]
@kobenguyent - seems to be over my skills to solve that issue ..

**Comment by kobenguyent** [comment]
> @kobenguyent - seems to be over my skills to solve that issue ..

Let me take a look if I could fix it.

**Comment by kobenguyent** [comment]
looks good for now @thomashohn

**Pull request merged**
