### PR TITLE
#2321 - Modified the allure.js to support for custom runners

### LINKED ISSUE #2321: OuputDir is undefined for allure plugin on using custom runner
I am trying to make a custom runner where the global.output_dir is being set correctly but the same is not reflecting in allure defaultConfig outputDir value which is throwing path error for writing to xml in allure 

Error Occured: 
    Error processing suite.after event:
    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at Object.writeSuite (C:\Users\mcharlie\node_modules\codeceptjs\node_modules\allure-js-commons\writer.js:9:32)
    at Allure.endSuite (C:\Users\mcharlie\node_modules\codeceptjs\node_modules\allure-js-commons\index.js:37:16)
    at EventEmitter.<anonymous> (C:\Users\mcharlie\node_modules\codeceptjs\lib\plugin\allure.js:192:14)
    at EventEmitter.emit (events.js:228:7)
    at EventEmitter.emit (domain.js:475:20)
    at Object.emit (C:\Users\mcharlie\node_modules\codeceptjs\lib\event.js:115:28)
    at C:\Users\mcharlie\node_modules\codeceptjs\lib\scenario.js:182:11
    at injectHook (C:\Users\mcharlie\node_modules\codeceptjs\lib\scenario.js:8:5)

```bash



allure.js Line# : 7
const defaultConfig = {
  outputDir: global.output_dir,
};

### Details

* CodeceptJS version: 2.5.0
* NodeJS Version: 12.15.0
* Operating System: Windows
* Configuration file:
exports.config = {
  output: './output',
  helpers:{
    WebDriver:{
      url:"myurl",
      browser:"chrome",
      desiredCapabilities:{
        'chromeOptions': {
          useAutomationExtension: false,
          args: [ 'start-maximized'],
 
          },
        },
      },
      host: 'localhost',
      port: 4444,
    },
  },
  include: {
    I: './steps_file.js'
  },
  
  bootstrap: null,
  teardown: null,
  hooks: [],
  gherkin: {
    features: './features/*.feature',
    steps: ['./step_definitions/steps.js']
  },
  plugins: {
    allure: {
      enabled: true,
      enableScreenshotDiffPlugin: true
    },
    screenshotOnFail: {
      enabled: true
    },
    wdio: {
      enabled: true,
      services: ['selenium-standalone']
    }
  },
};

### PR DESCRIPTION
**Pull request by charliepradeep**
## Motivation/Description of the PR
- Description of this PR, which problem it solves
- Resolves #2321.

Applicable helpers:

- [ ] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [ ] Playwright

Applicable plugins:

- [x] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] puppeteerCoverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] wdio

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [x] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

[ForkLint.txt](https://github.com/Codeception/CodeceptJS/files/4449967/ForkLint.txt)
[ForkTest.txt](https://github.com/Codeception/CodeceptJS/files/4449968/ForkTest.txt)

### CODE REVIEW

**Comment by PeterNgTr** [comment]
@charliepradeep could you setup tests for this?

**Comment by charliepradeep** [comment]
@PeterNgTr  Could you please help me on setting up test or can you suggest me what kind of test I need to write?

If you can please provide me a sample test file.

**Comment by PeterNgTr** [comment]
> @PeterNgTr Could you please help me on setting up test or can you suggest me what kind of test I need to write?
> 
> If you can please provide me a sample test file.

maybe this gives you an idea :) https://github.com/Codeception/CodeceptJS/blob/master/test/runner/allure_test.js

**Comment by charliepradeep** [comment]
> > @PeterNgTr Could you please help me on setting up test or can you suggest me what kind of test I need to write?
> > If you can please provide me a sample test file.
> 
> maybe this gives you an idea :) https://github.com/Codeception/CodeceptJS/blob/master/test/runner/allure_test.js

Thanks for your support @PeterNgTr. 

Added the test file. 
[testReport.txt](https://github.com/Codeception/CodeceptJS/files/4452028/testReport.txt)

**Comment by Vorobeyko** [comment]
@charliepradeep Hi! Are you need patch release for this changed?

**Comment by charliepradeep** [comment]
@Vorobeyko : If it's a patch release it would be helpful.

**Comment by DavertMik** [comment]
Thank you!

**Comment by charliepradeep** [comment]
Thank you @DavertMik, @Vorobeyko and @PeterNgTr  👍

**Pull request merged**
