### PR TITLE
Fix compile error

### PR DESCRIPTION
**Pull request by trollr**

### CODE REVIEW

**Comment by galkin** [comment]
hi, @trollr!
Thx for pull request. What node.js version do you use? Could you share result of command:
`node -v`

**Comment by trollr** [comment]
it's the node version from codeceptjs:latest docker image -> v6.9.5

**Comment by DavertMik** [comment]
@trollr thanks, we are in process of migrating to Node 8. See https://github.com/Codeception/CodeceptJS/issues/795

Current codebase may be changing due to this. Stick to stable releases or upgrade Node.
Docker image is about to be updated as well

**Comment by DavertMik** [comment]
Thanks. that looked like autofixer failure.

**Comment by trollr** [comment]
Oh nice, but we need a stable image to test our b2b eCommerce plattform :) could you tag it in docker hub?

**Comment by DavertMik** [comment]
Please use `:1.0.3` tag.
Sorry, I forgot that `latest` refers to the master branch. Which may be unstable in some cases.

**Comment by trollr** [comment]
`:1.0.3` is 3 months old and crash with:

`codeceptjs_1             | Error: Cannot find module '/codecept/bin/codecept.js'
codeceptjs_1             |     at Function.Module._resolveFilename (module.js:469:15)
codeceptjs_1             |     at Function.Module._load (module.js:417:25)
codeceptjs_1             |     at Module.runMain (module.js:604:10)
codeceptjs_1             |     at run (bootstrap_node.js:394:7)
codeceptjs_1             |     at startup (bootstrap_node.js:149:9)
codeceptjs_1             |     at bootstrap_node.js:509:3`

**Comment by DavertMik** [comment]
Ok, thanks. I fix this

**Pull request merged**
